---
title: "makeCowell2006Figs"
author: "pss"
date: "May 30, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(tidyr)
setwd("~/uMass/firstYear/VDModel_fg/RScripts/plotting_dp")
```

## Delay

```{r, loadData1}

f <- paste(getwd(),'delay', 'recog_rats_new.csv', sep = "/")

d <- read.csv(f, header=FALSE) %>%
  rename(., rat = V6, sess1=V1, sess2=V2, sess3=V3, sess4=V4, sess5=V5) %>%
  gather(., key = session, value=recog, sess1:sess5) %>%
  mutate(., group = rep(c('PRC Lesion Group', 'Control'), each=6, times=5))

```

```{r, plot1}

# arrange and summarise
group_by(d, session, group) %>%
  summarise(avg = mean(recog), SD = sd(recog), N = n()) %>%
  mutate(SEM = SD/sqrt(N),
         upper = avg + SEM*qt(.975, N-1,lower.tail = F),
         lower = avg - SEM*qt(.975, N-1,lower.tail = F)) %>%
  
  # pull out the plots
  ggplot(., aes(x=session, y = avg, shape=group)) +
  geom_line(lwd=1, aes(group=group)) +
  geom_point(size = 7) +
  scale_shape_manual(values=c(19,1), name = NULL) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = .15) +
  scale_x_discrete("Delay",labels = c('0', '2000', '4000', '6000', '8000')) +
  scale_y_continuous("Recognition Score", limits = c(0,.2), expand = c(0,0)) +
  geom_segment(aes(x=1, xend=5, y=0, yend=0)) +
  theme(axis.ticks.y = element_blank(), 
        axis.text.y = element_blank(), 
        text = element_text(size=35), 
        axis.ticks.x = element_line(size=1), 
        axis.ticks.length=unit(.25,"cm"), 
        legend.position=c(.75, .75),
        legend.key.height=unit(2,"line"), 
        legend.key = element_rect(fill=NA, colour=NA),
        panel.background = element_blank(),
        plot.margin=unit(c(0,0,.25,0),"cm")) +
  ggsave(file = 'recog_delay.png')


```


## List length


```{r, loadData2}

f <- paste(getwd(),'listLength', 'recog_rats.csv', sep = "/")

d <- read.csv(f, header=FALSE) %>%
  rename(., rat = V5, sess1=V1, sess2=V2, sess3=V3, sess4=V4) %>%
  gather(., key = session, value=recog, sess1:sess4) %>%
  mutate(., group = rep(c('PRC Lesion Group', 'Control'), each=6, times=4))

```

```{r, plot2}

# arrange and summarise
group_by(d, session, group) %>%
  summarise(avg = mean(recog), SD = sd(recog), N = n()) %>%
  mutate(SEM = SD/sqrt(N),
         upper = avg + SEM*qt(.975, N-1,lower.tail = F),
         lower = avg - SEM*qt(.975, N-1,lower.tail = F)) %>%
  
  # pull out the plots
  ggplot(., aes(x=session, y = avg, shape=group)) +
  geom_line(lwd=1, aes(group=group)) +
  geom_point(size = 7) +
  scale_shape_manual(values=c(19,1), name = NULL) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = .15) +
  scale_x_discrete("List Length",labels = c('1', '6', '12', '18')) +
  scale_y_continuous("Recognition Score", limits = c(0,.2), expand = c(0,0)) +
  geom_segment(aes(x=1, xend=4, y=0, yend=0)) +
  theme(axis.ticks.y = element_blank(), 
        axis.text.y = element_blank(), 
        text = element_text(size=35), 
        axis.ticks.x = element_line(size=1), 
        axis.ticks.length=unit(.25,"cm"), 
        legend.position=c(.75, .9),
        legend.key.height=unit(2,"line"), 
        legend.key = element_rect(fill=NA, colour=NA),
        panel.background = element_blank(),
        plot.margin=unit(c(0,0,.25,0),"cm")) +
  ggsave(file = 'recog_ll.png')



```

## Trial Unique


```{r, loadData3}

f <- paste(getwd(),'tUnique', 'recog_rats.csv', sep = "/")

d <- read.csv(f, header=FALSE) %>%
  rename(., rat = V3, sess1=V1, sess2=V2) %>%
  gather(., key = session, value=recog, sess1:sess2) %>%
  mutate(., group = rep(c('PRC Lesion Group', 'Control'), each=6, times=2))

```

```{r, plot3}
pd = position_dodge(width=1)

# arrange and summarise
group_by(d, session, group) %>%
  summarise(avg = mean(recog), SD = sd(recog), N = n()) %>%
  mutate(SEM = SD/sqrt(N),
         upper = avg + SEM*qt(.975, N-1,lower.tail = F),
         lower = avg - SEM*qt(.975, N-1,lower.tail = F)) %>%
  
  # pull out the plots
  ggplot(., aes(x=session, y = avg)) +
  geom_bar(stat='identity', position=pd, aes(fill=group), colour='black') +
  geom_errorbar(aes(ymin = lower, ymax = upper, group=group), width = .15, position=pd) +
  scale_fill_manual(values = c('black', 'white'), name=element_blank()) +
  scale_x_discrete("Condition",labels = c('Trial Unique', 'Repeating')) +
  scale_y_continuous("Recognition Score", limits = c(0,.2)) +
  geom_segment(aes(x=.5, xend=2.5, y=0, yend=0)) +
  theme(axis.ticks.y = element_blank(), 
        axis.text.y = element_blank(), 
        text = element_text(size=35), 
        axis.ticks.x = element_line(size=1), 
        axis.ticks.length=unit(0,"cm"), 
        legend.position=c(.75, .75),
        legend.key.height=unit(2,"line"), 
        legend.key = element_rect(fill=NA, colour=NA),
        panel.background = element_blank(),
        plot.margin=unit(c(0,0,.25,0),"cm"),
        strip.text.x = element_blank()) +
  ggsave(file = 'recog_tUnique.png')



```
