---
title: "makeDelayGraph"
author: "pss"
date: "May 30, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(tidyr)
setwd("~/uMass/firstYear/VDModel_fg/RScripts/plotting_dp")
```

```{r, loadData}

f <- paste(getwd(),'delay', 'recog_rats.csv', sep = "/")

d <- read.csv(f, header=FALSE) %>%
  rename(., rat = V6, sess1=V1, sess2=V2, sess3=V3, sess4=V4, sess5=V5) %>%
  gather(., key = session, value=recog, sess1:sess5) %>%
  mutate(., group = rep(c('Control', 'PRC Lesion Group'), each=6, times=5))

```

```{r, plot}


group_by(d, session, group) %>%
  summarise(avg = mean(recog), SD = sd(recog), N = n()) %>%
  mutate(SEM = SD/sqrt(N),
         upper = avg + SEM*qt(.975, N-1,lower.tail = F),
         lower = avg - SEM*qt(.975, N-1,lower.tail = F)) %>%
  
  # pull out the plots
  ggplot(., aes(x=session, y = avg, shape=group)) +
  geom_line(lwd=1, aes(group=group)) +
  geom_point(size = 5) +
  scale_shape_manual(values=c(19,1)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = .15) +
  scale_x_discrete("Delay", labels = c('0', '2000', '4000', '6000', '8000')) +
  ylab("Recognition Score") +
  theme(axis.ticks = element_blank(), axis.text.y = element_blank(), text = element_text(size=20)) +
  theme(legend.position=c(.75, .75)) +
  theme(panel.background = element_rect(fill = 'white', colour = 'white'))


```