---
title: "plot_dp"
author: "pss"
date: "May 30, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(tidyr)
```

```{r, fns}
# useful functions

# load every .csv file in a directory (including subdirectories) and place in single dataframe
load_data <- function(path) { 
  files <- dir(path, pattern = '\\.csv', full.names = TRUE, recursive = TRUE)
  tables <- lapply(files, read.csv, header=FALSE)
  do.call(rbind, tables)
}


```

```{r, loadData}

## NOTE: although rats will come out as only being from 1-6, each rat 1 is slightly different (indicated by how many dims it had to deal with during input


p <- file.path('D:','documents', 'uMass', 'firstYear', 'VDModel_fg', 'current', 'cowell2006', 'allExpts', 'graphsAndSession', 'listLength', 'all')

d <- load_data(p) %>%
  rename(., rat = V5, dims=V6, sess1=V1, sess2=V2, sess3=V3, sess4=V4) %>%
  gather(., key = session, value=recog, sess1:sess4)

```


```{r, plot}

group_by(d, dims, session) %>%
  summarise(., avg = mean(recog)) %>%
  filter(., session == c('sess1','sess4')) %>%
  spread(., session,avg) %>%
  mutate(ratio = sess4 / sess1) %>%
  ggplot(., aes(x=dims, y = ratio)) +
  geom_point() +
  xlab("Dimensionality of Representation") + 
  ylab("Recognition Ratio (session 1) / (session 4)")

```



```{r, test}

# Add a primary key
iris_normal <- mutate(iris, FlowerID = row_number(Species)) %>%
# change layout to long-form
  gather(key = variable, value = size, Sepal.Length:Petal.Width) %>%
# Break "Sepal/Petal" & "Length/Width" into 2 columns
  separate(variable, c("Structure", "dimension"))

# Make a variable for length and width each  
iris_long <- spread(iris_normal, dimension, size)



iris_means <- iris_normal %>%
  group_by(Species, Structure, dimension) %>%
  summarise(avg = mean(size), SD = sd(size), N = n()) %>%
  mutate(SEM = SD/sqrt(N),
         upper = avg + SEM*qt(.975, N-1,lower.tail = F),
         lower = avg - SEM*qt(.975, N-1,lower.tail = F))
```
