
% lesion, then control
dPrime1_first = [2.25, 3.3 , 2.7, 3.5];
dPrime1_second = [.5, 3.3 , 2.8, 3.7];

dPrime1_first_err = [1/sqrt(2), .5/sqrt(2), .1, .1];
dPrime1_second_err = [.5/sqrt(2), .5/sqrt(2) , .1, .1];


% lesion, then control
dPrime2_lesion = [2.4, 1.7, 2.5];
dPrime2_control = [2.4, 2.6, 2.6];

dPrime2_lesion_err = [std([2.3,2.5])/sqrt(2), std([1.5,1.9])/sqrt(2), std([2.4,2.6])/sqrt(2)];
dPrime2_control_err = [std([2.3,2.5])/sqrt(2), std([2.5,2.7])/sqrt(2), std([2.4,2.8])/sqrt(2)];


%% task 1
figs(1) = figure;
subplot(1,2,1)
barweb([dPrime1_first(1), dPrime1_second(1) ; dPrime1_first(2), dPrime1_second(2)]...
    , [dPrime1_first_err(1), dPrime1_second_err(1) ; dPrime1_first_err(2), dPrime1_second_err(2)]...
    , [] ...
    , {'High', 'Low'}...
    , {'Lesion'}...
    , {'Stimulus Ambiguity'}...
    , {'d'''});
legend('First Half', 'Second Half','Location','NorthWest');
legend BOXOFF
set(gca,'fontsize',30)
figs(1).CurrentAxes.YLim = [0, 5];
set(findall(gcf,'type','text'),'FontSize',30,'fontWeight','bold')

subplot(1,2,2)
barweb([dPrime1_first(3), dPrime1_second(3) ; dPrime1_first(4), dPrime1_second(4)]...
    , [dPrime1_first_err(3), dPrime1_second_err(3) ; dPrime1_first_err(4), dPrime1_second_err(4)]...
    , [] ...
    , {'High', 'Low'}...
    , {'Control'}...
    , {'Stimulus Ambiguity'}...
    , {'d'''});
legend('First Half', 'Second Half','Location','NorthWest');
legend BOXOFF
set(gca,'fontsize',30)
figs(1).CurrentAxes.YLim = [0, 5];
set(findall(gcf,'type','text'),'FontSize',30,'fontWeight','bold')

%% task 2
figs(2) = figure;
subplot(1,2,1)
barweb([dPrime2_lesion(1), dPrime2_lesion(2), dPrime2_lesion(3)]...
    , [dPrime2_lesion_err(1), dPrime2_lesion_err(2), dPrime2_lesion_err(3)]...
    , [] ...
    , {'High', 'Low'}...
    , {'Lesion'}...
    , {'Stimulus Ambiguity'}...
    , {'d'''});
legend('Low Ambiguity 1', 'High Ambiguity ', 'Low Ambiguity 2','Location','NorthWest');
legend BOXOFF
set(gca,'fontsize',30)
figs(2).CurrentAxes.YLim = [0, 5];
set(findall(gcf,'type','text'),'FontSize',30,'fontWeight','bold')

subplot(1,2,2)
barweb([dPrime2_control(1), dPrime2_control(2), dPrime2_control(3)]...
    , [dPrime2_control_err(1), dPrime2_control_err(2), dPrime2_control_err(3)]...
    , [] ...
    , {'High', 'Low'}...
    , {'Control'}...
    , {'Stimulus Ambiguity'}...
    , {'d'''});
legend('Low Ambiguity 1', 'High Ambiguity ', 'Low Ambiguity 2', 'Location','NorthWest');
legend BOXOFF
set(gca,'fontsize',30)
figs(2).CurrentAxes.YLim = [0, 5];
set(findall(gcf,'type','text'),'FontSize',30,'fontWeight','bold')


